name: FastAPI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests (If Any)
      run: |
        python -m unittest discover tests || echo "No tests found, skipping."

    - name: Log in to Docker Hub    
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
    
    - name: Tag Docker Image
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest ${{ secrets.DOCKER_USERNAME }}/fastapi-app:v1
    
    - name: Push Docker Images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:v1
    
